create type game_status as enum ('pending', 'started', 'complete');

create table games (
  id bigint generated by default as identity primary key,
  channel uuid default uuid_generate_v4() not null,
  status game_status default 'pending' not null,
  host_id uuid references auth.users (id) default auth.uid() not null
);

create table players (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score int default 0 not null,
  game_id bigint references games (id) not null,
  user_id uuid references auth.users (id) default auth.uid() not null,
  unique(game_id, user_id)
);

alter publication supabase_realtime add table public.players;
