name: supaquiz
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  hashids2: ^2.0.0
  json_serializable: ^6.5.4
  shared_preferences: ^2.0.15
  supabase_flutter: ^1.2.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true