name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean
      - run: echo $SECRETS_FILE | base64 -d > lib/secrets.dart
        env:
          SECRETS_FILE: ${{ secrets.SECRETS_FILE }}
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build
          mkdir web-deploy
          cd web-deploy
          git config --global user.email christos@dartling.dev
          git config --global user.name yallurium
          git config --global init.defaultBranch main
          git init
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/yallurium/supaquiz.git
          git fetch origin gh-pages
          git switch gh-pages
          cp -R ../web/* .
          git status
          git add .
          echo ""
          echo "Committing to gh-pages: ${{ github.event.head_commit.message }}"
          echo ""
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin gh-pages
